import {
  JobVacancy,
  CategoryAnalyticsPayload,
  FilterMetadataPayload,
  DashboardDataPayload,
} from "@/types/job";

// ============================================================================
// Mock: GET /vacancies/filter-values
// ============================================================================
export const MOCK_FILTER_METADATA: FilterMetadataPayload = {
  categories: [
    { value: "IT" },
    { value: "Medicine" },
    { value: "Construction" },
    { value: "Furniture Design" },
    { value: "Marketing" },
    { value: "Human Resources" },
    { value: "Banking & Finance" },
    { value: "Retail" },
    { value: "Supply Chain" },
    { value: "Quality Assurance" },
    { value: "Healthcare Administration" },
    { value: "Customer Service" },
  ],
  provinces: [
    { id: 1, name: "Western", vacancies: 2840 },
    { id: 2, name: "Central", vacancies: 980 },
    { id: 3, name: "Southern", vacancies: 760 },
    { id: 4, name: "Northern", vacancies: 310 },
    { id: 5, name: "Eastern", vacancies: 420 },
    { id: 6, name: "North Western", vacancies: 640 },
    { id: 7, name: "North Central", vacancies: 390 },
    { id: 8, name: "Uva", vacancies: 270 },
    { id: 9, name: "Sabaragamuwa", vacancies: 310 },
  ],
  contractTypes: [
    { value: "Full Time" },
    { value: "Part Time" },
    { value: "Contract" },
    { value: "Freelance" },
    { value: "Internship" },
  ],
  seniorityLevels: [
    { value: "Entry-level" },
    { value: "Junior" },
    { value: "Mid Level" },
    { value: "Senior" },
  ],
};

// ============================================================================
// Mock: GET /analytics/dashboard
// ============================================================================
export const MOCK_DASHBOARD_DATA: DashboardDataPayload = {
  kpiSummary: {
    totalVacancies: 13560,
    vacancyGrowthPct: 12.4,
    sectorsTracked: 42,
    skillsIdentified: 846,
  },
  categoryData: [
    { category: "Software Engineering", vacancies: 5400 },
    { category: "Data Science & AI", vacancies: 2800 },
    { category: "DevOps & Cloud Systems", vacancies: 2100 },
    { category: "Product Management", vacancies: 1800 },
    { category: "Quality Assurance Automation", vacancies: 1460 },
  ],
  monthlyTrends: [
    { month: "Jun 2025", vacancies: 5300 },
    { month: "Jul 2025", vacancies: 5750 },
    { month: "Aug 2025", vacancies: 6200 },
    { month: "Sep 2025", vacancies: 6700 },
    { month: "Oct 2025", vacancies: 6850 },
    { month: "Nov 2025", vacancies: 6900 },
    { month: "Dec 2025", vacancies: 7500 },
    { month: "Jan 2026", vacancies: 7750 },
    { month: "Feb 2026", vacancies: 8300 },
    { month: "Mar 2026", vacancies: 8700 },
    { month: "Apr 2026", vacancies: 9050 },
    { month: "May 2026", vacancies: 9560 },
  ],
  ingestionSources: [
    { name: "TopJobs", vacancies: 4850 },
    { name: "Ikman Jobs", vacancies: 3920 },
    { name: "XpressJobs", vacancies: 2840 },
    { name: "LinkedIn Native", vacancies: 1950 },
  ],
  leadingEmployers: [
    { name: "WSO2", openRoles: 142, location: "Colombo, Western", sector: "Technology" },
    { name: "Dialog Axiata", openRoles: 98, location: "Colombo, Western", sector: "Telecommunications" },
    { name: "John Keells Holdings", openRoles: 84, location: "Colombo, Western", sector: "Conglomerate" },
    { name: "IFS Sri Lanka", openRoles: 76, location: "Colombo, Western", sector: "Technology" },
    { name: "LSEG Technology", openRoles: 69, location: "Colombo, Western", sector: "Fintech" },
  ],
  distributionTracks: {
    seniority: [
      { name: "Mid-Level Professional", share: 45 },
      { name: "Junior / Associate", share: 25 },
      { name: "Senior Staff", share: 22 },
      { name: "Lead / Principal Architect", share: 8 },
    ],
    contractTypes: [
      { name: "Full-Time Corporate", share: 70 },
      { name: "Independent Contract", share: 15 },
      { name: "Part-Time Engagement", share: 10 },
      { name: "Graduate Internship", share: 5 },
    ],
    remoteConfiguration: [
      { name: "Office Based", share: 65 },
      { name: "Remote Available", share: 35 },
    ],
  },
  // Province-level — province string matches the lowercase province key used in SRI_LANKA_DISTRICTS
  districtGeoData: [
    { id: "western",      province: "Western",      jobs: 8740, nationalShare: 34.5 },
    { id: "central",      province: "Central",      jobs: 4250, nationalShare: 16.8 },
    { id: "southern",     province: "Southern",     jobs: 2760, nationalShare: 10.9 },
    { id: "northern",     province: "Northern",     jobs: 1890, nationalShare: 7.5  },
    { id: "eastern",      province: "Eastern",      jobs: 1320, nationalShare: 5.2  },
    { id: "northwestern", province: "North Western", jobs: 2050, nationalShare: 8.1 },
    { id: "northcentral", province: "North Central", jobs: 1120, nationalShare: 4.4 },
    { id: "uva",          province: "Uva",          jobs: 840,  nationalShare: 3.3  },
    { id: "sabaragamuwa", province: "Sabaragamuwa", jobs: 590,  nationalShare: 2.3  },
  ],
};

// ============================================================================
// Mock: GET /analytics/category/{category}
// ============================================================================
export const MOCK_ANALYTICS_DATA: Record<string, CategoryAnalyticsPayload> = {
  "All Categories": {
    skills: [
      { skill: "TypeScript / React", demand: 4250, category: "IT" },
      { skill: "Critical Care Nursing", demand: 3900, category: "Medicine" },
      { skill: "Cloud Architecture (AWS/Azure)", demand: 3800, category: "IT" },
      { skill: "BIM Modelling (Revit)", demand: 2450, category: "Construction" },
    ],
    provinces: [
      { id: 1, name: "Western", vacancies: 14850 },
      { id: 2, name: "Central", vacancies: 5900 },
      { id: 3, name: "Southern", vacancies: 4200 },
      { id: 6, name: "North Western", vacancies: 2100 },
      { id: 4, name: "Northern", vacancies: 1800 },
    ],
    employers: [
      { name: "Virtusa Labs", openRoles: 320, location: "Western Province", sector: "IT" },
      { name: "Asiri Health Group", openRoles: 240, location: "Multi-Region", sector: "Medicine" },
    ],
  },
  "IT": {
    skills: [
      { skill: "TypeScript / React", demand: 4250, category: "IT" },
      { skill: "Cloud Architecture (AWS/Azure)", demand: 3800, category: "IT" },
      { skill: "Python & Machine Learning", demand: 3100, category: "IT" },
      { skill: "Node.js & REST APIs", demand: 2800, category: "IT" },
      { skill: "DevOps / Kubernetes", demand: 2200, category: "IT" },
    ],
    provinces: [
      { id: 1, name: "Western", vacancies: 11800 },
      { id: 2, name: "Central", vacancies: 1400 },
      { id: 3, name: "Southern", vacancies: 900 },
    ],
    employers: [
      { name: "Virtusa Labs", openRoles: 320, location: "Western Province", sector: "IT" },
      { name: "Sysco LABS", openRoles: 180, location: "Western Province", sector: "IT" },
    ],
  },
  "Medicine": {
    skills: [
      { skill: "Critical Care Nursing", demand: 3900, category: "Medicine" },
      { skill: "Health Informatics & EHR", demand: 2600, category: "Medicine" },
      { skill: "Surgical Assistance", demand: 1800, category: "Medicine" },
    ],
    provinces: [
      { id: 1, name: "Western", vacancies: 4100 },
      { id: 2, name: "Central", vacancies: 2600 },
      { id: 3, name: "Southern", vacancies: 1500 },
    ],
    employers: [
      { name: "Asiri Health Group", openRoles: 240, location: "Multi-Region", sector: "Medicine" },
      { name: "Nawaloka Hospitals", openRoles: 140, location: "Western Province", sector: "Medicine" },
    ],
  },
  "Construction": {
    skills: [
      { skill: "BIM Modelling (Revit)", demand: 2450, category: "Construction" },
      { skill: "Structural Engineering CAD", demand: 2200, category: "Construction" },
      { skill: "Project Management (PMP)", demand: 1600, category: "Construction" },
    ],
    provinces: [
      { id: 1, name: "Western", vacancies: 5200 },
      { id: 2, name: "Central", vacancies: 1900 },
      { id: 3, name: "Southern", vacancies: 1200 },
    ],
    employers: [
      { name: "Access Engineering", openRoles: 195, location: "Western Province", sector: "Construction" },
      { name: "MAGA Engineering", openRoles: 160, location: "Western Province", sector: "Construction" },
    ],
  },
};

// ============================================================================
// Mock: GET /vacancies
// ============================================================================
export const MOCK_VACANCIES: JobVacancy[] = [
  {
    id: "vac_001",
    employer: "Rimaco Furniture Pvt Ltd.",
    job_role: "3D Sketchup Designer",
    job_type: "Full Time",
    key_responsibilities: "Creating 3D designs using Sketchup software for MDF furniture manufacturing.",
    qualifications: "Ordinary Level (OL) education; ability to type in English and Sinhala; age above 18; no prior experience required.",
    location: "Boralesgamuwa, Colombo",
    offers: "Salary negotiable; priority given to applicants from Maharagama and Boralesgamuwa areas.",
    is_remote: false,
    skills: ["Sketchup", "3D Design", "MDF Manufacturing"],
    meta_data: {
      posted_at: "2026-05-14T08:30:00Z",
      source: "TopJobs.lk",
      standardized_category: "IT",
      seniority: "Entry-level",
      geo: {
        id: 1,
        lat: 6.8488, lng: 79.9101, province: "Western"
      },
      confidence_score: 0.98,
      ai_version: "gemini-2.0-flash-v1",
      error: false,
    },
  },
  {
    id: "vac_002",
    employer: "Softlogic Holdings PLC",
    job_role: "Junior Software Engineer",
    job_type: "Full Time",
    key_responsibilities: "Developing and maintaining web applications using React and Node.js.",
    qualifications: "Diploma or degree in IT/Computer Science; basic knowledge of JavaScript frameworks.",
    location: "Colombo 03",
    offers: "Health insurance, annual bonuses, and hybrid work opportunities.",
    is_remote: true,
    skills: ["React", "Node.js", "JavaScript", "REST APIs"],
    meta_data: {
      posted_at: "2026-05-12T09:00:00Z",
      source: "LinkedIn",
      standardized_category: "IT",
      seniority: "Junior",
      geo: { id: 2, lat: 6.9271, lng: 79.8612, province: "Western" },
      confidence_score: 0.97,
      ai_version: "gemini-2.0-flash-v1",
      error: false,
    },
  },
  {
    id: "vac_003",
    employer: "Dialog Axiata PLC",
    job_role: "Customer Support Executive",
    job_type: "Full Time",
    key_responsibilities: "Handling customer inquiries and resolving service-related issues via phone and email.",
    qualifications: "Excellent communication skills in Sinhala and English; prior customer service experience preferred.",
    location: "Kandy",
    offers: "EPF/ETF, performance incentives, and career growth opportunities.",
    is_remote: false,
    skills: ["Communication", "Customer Service", "CRM"],
    meta_data: {
      posted_at: "2026-05-10T11:15:00Z",
      source: "TopJobs.lk",
      standardized_category: "Customer Service",
      seniority: "Mid Level",
      geo: { id: 3, lat: 7.2906, lng: 80.6337, province: "Central" },
      confidence_score: 0.96,
      ai_version: "gemini-2.0-flash-v1",
      error: false,
    },
  },
  {
    id: "vac_004",
    employer: "MAS Holdings",
    job_role: "HR Assistant",
    job_type: "Full Time",
    key_responsibilities: "Assisting recruitment processes and maintaining employee records.",
    qualifications: "Degree or diploma in Human Resource Management; proficiency in MS Office.",
    location: "Katunayake",
    offers: "Transport facilities, meals, and training programs.",
    is_remote: false,
    skills: ["HR Management", "Recruitment", "MS Office"],
    meta_data: {
      posted_at: "2026-05-08T07:45:00Z",
      source: "XpressJobs",
      standardized_category: "Human Resources",
      seniority: "Entry-level",
      geo: { id: 4, lat: 7.1699, lng: 79.8841, province: "Western" },
      confidence_score: 0.95,
      ai_version: "gemini-2.0-flash-v1",
      error: false,
    },
  },
  {
    id: "vac_005",
    employer: "Commercial Bank of Ceylon",
    job_role: "Banking Assistant",
    job_type: "Full Time",
    key_responsibilities: "Managing customer transactions and supporting daily banking operations.",
    qualifications: "Passed GCE A/L; strong numerical and interpersonal skills.",
    location: "Galle",
    offers: "Medical insurance and annual performance bonuses.",
    is_remote: false,
    skills: ["Banking", "Cash Handling", "Customer Relations"],
    meta_data: {
      posted_at: "2026-05-15T10:20:00Z",
      source: "Observer Jobs",
      standardized_category: "Banking & Finance",
      seniority: "Entry-level",
      geo: { id: 5, lat: 6.0535, lng: 80.2210, province: "Southern" },
      confidence_score: 0.94,
      ai_version: "gemini-2.0-flash-v1",
      error: false,
    },
  },
  {
    id: "vac_006",
    employer: "Virtusa Sri Lanka",
    job_role: "QA Engineer",
    job_type: "Full Time",
    key_responsibilities: "Performing manual and automated software testing for enterprise applications.",
    qualifications: "Degree in Computer Science or related field; knowledge of Selenium is an advantage.",
    location: "Colombo 01",
    offers: "Flexible working hours and learning opportunities.",
    is_remote: true,
    skills: ["QA Testing", "Selenium", "Automation"],
    meta_data: {
      posted_at: "2026-05-11T14:40:00Z",
      source: "LinkedIn",
      standardized_category: "Quality Assurance",
      seniority: "Junior",
      geo: { id: 6, lat: 6.9344, lng: 79.8428, province: "Western" },
      confidence_score: 0.98,
      ai_version: "gemini-2.0-flash-v1",
      error: false,
    },
  },
  {
    id: "vac_007",
    employer: "Cargills Food City",
    job_role: "Cashier",
    job_type: "Part Time",
    key_responsibilities: "Handling billing operations and assisting customers at checkout counters.",
    qualifications: "GCE O/L qualification; friendly personality and basic computer literacy.",
    location: "Negombo",
    offers: "Flexible shifts and overtime payments.",
    is_remote: false,
    skills: ["POS Systems", "Customer Handling", "Cash Management"],
    meta_data: {
      posted_at: "2026-05-13T16:00:00Z",
      source: "TopJobs.lk",
      standardized_category: "Retail",
      seniority: "Entry-level",
      geo: { id: 7, lat: 7.2084, lng: 79.8358, province: "Western" },
      confidence_score: 0.93,
      ai_version: "gemini-2.0-flash-v1",
      error: false,
    },
  },
  {
    id: "vac_008",
    employer: "PickMe",
    job_role: "Digital Marketing Executive",
    job_type: "Full Time",
    key_responsibilities: "Planning and executing social media campaigns and digital advertisements.",
    qualifications: "Degree or diploma in Marketing; experience with Meta Ads and Google Ads preferred.",
    location: "Colombo 05",
    offers: "Performance bonuses and hybrid work model.",
    is_remote: true,
    skills: ["Digital Marketing", "SEO", "Google Ads", "Social Media"],
    meta_data: {
      posted_at: "2026-05-09T12:30:00Z",
      source: "LinkedIn",
      standardized_category: "Marketing",
      seniority: "Mid Level",
      geo: { id: 8, lat: 6.8916, lng: 79.8547, province: "Western" },
      confidence_score: 0.97,
      ai_version: "gemini-2.0-flash-v1",
      error: false,
    },
  },
  {
    id: "vac_009",
    employer: "Lanka Hospitals",
    job_role: "Receptionist",
    job_type: "Full Time",
    key_responsibilities: "Managing front desk operations and coordinating patient appointments.",
    qualifications: "Good communication skills and prior front-office experience preferred.",
    location: "Colombo 06",
    offers: "Uniform allowance and medical benefits.",
    is_remote: false,
    skills: ["Reception", "Communication", "Scheduling"],
    meta_data: {
      posted_at: "2026-05-16T08:10:00Z",
      source: "XpressJobs",
      standardized_category: "Healthcare Administration",
      seniority: "Entry-level",
      geo: { id: 9, lat: 6.8741, lng: 79.8590, province: "Western" },
      confidence_score: 0.95,
      ai_version: "gemini-2.0-flash-v1",
      error: false,
    },
  },
  {
    id: "vac_010",
    employer: "Hayleys PLC",
    job_role: "Logistics Coordinator",
    job_type: "Contract",
    key_responsibilities: "Coordinating shipments and maintaining inventory and logistics records.",
    qualifications: "Diploma in Supply Chain Management; knowledge of ERP systems preferred.",
    location: "Kurunegala",
    offers: "Travel allowance and career advancement opportunities.",
    is_remote: false,
    skills: ["Logistics", "Inventory Management", "ERP"],
    meta_data: {
      posted_at: "2026-05-17T13:25:00Z",
      source: "Observer Jobs",
      standardized_category: "Supply Chain",
      seniority: "Mid Level",
      geo: { id: 10, lat: 7.4863, lng: 80.3623, province: "North Western" },
      confidence_score: 0.96,
      ai_version: "gemini-2.0-flash-v1",
      error: false,
    },
  },
];