apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  CRAWLER_API_URL: {{ .Values.config.crawlerApiUrl | quote }}
  THUNDER_BASE_URL: {{ .Values.config.thunderBaseUrl | quote }}
  THUNDER_ISSUER: {{ .Values.config.thunderIssuer | quote }}
  THUNDER_AUDIENCE: {{ .Values.config.thunderAudience | quote }}
  THUNDER_INSECURE_TLS: {{ .Values.config.thunderInsecureTls | quote }}