name: Build Crawler

on:
  push:
    branches: ["main"]
    paths:
      - 'engineering/crawler/**'
      - '.github/workflows/crawler.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'engineering/crawler/**'
      - '.github/workflows/crawler.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Crawler Image
        uses: docker/build-push-action@v6
        with:
          context: ./engineering/crawler
          file: ./engineering/crawler/Dockerfile
          push: false
          tags: crawler:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max